# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CommaSeparatedIntegerField(max_length=20)),
                ('algorithm', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('pathlength', models.CharField(max_length=20)),
                ('nowtime', models.DateTimeField(auto_now=True)),
                ('inputjson', models.CharField(max_length=10000)),
                ('outputjson', models.CharField(max_length=10000)),
            ],
        ),
    ]
